export { default as Header } from './header/Header'
export { default as Main } from './main/Main'
export { default as Button } from './common/Button'
export {default as Logo} from './header/Logo'
export {default as ThemeToggler} from './common/ThemeToggler'
export { default as Background } from './common/Background'
export {default as Steps} from './main/Steps'
export {default as Skips} from './main/Skips'
export {default as BackToTop} from './common/BackToTop'